apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crucible.fullname" . }}-rabbitmq-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
data:
  definitions.json: |
    {
      "rabbit_version": "3.13.0",
      "users": [
        {
          "name": {{ .Values.rabbitmq.auth.username | quote }},
          "password_hash": "CfDJ8NvAikc16nEv2MqAQPGnuBxzwH+r5N8pXFWIOxBqzEFbIG==",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "administrator"
        }
      ],
      "vhosts": [{ "name": "/" }],
      "permissions": [
        {
          "user": {{ .Values.rabbitmq.auth.username | quote }},
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "queues": [],
      "exchanges": [],
      "bindings": []
    }
