{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crucible.fullname" . }}-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
    {{- include "crucible.selectorLabels" (dict "root" . "component" "rabbitmq") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: amqp
      protocol: TCP
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
      protocol: TCP
  selector:
    {{- include "crucible.selectorLabels" (dict "root" . "component" "rabbitmq") | nindent 4 }}
{{- end }}
