{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crucible.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
    {{- include "crucible.selectorLabels" (dict "root" . "component" "postgresql") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "crucible.selectorLabels" (dict "root" . "component" "postgresql") | nindent 4 }}
{{- end }}
