{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crucible.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
    {{- include "crucible.selectorLabels" (dict "root" . "component" "prometheus") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "crucible.selectorLabels" (dict "root" . "component" "prometheus") | nindent 4 }}
{{- end }}
