apiVersion: v1
kind: Service
metadata:
  name: {{ include "crucible.fullname" . }}-control-plane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
    {{- include "crucible.selectorLabels" (dict "root" . "component" "control-plane") | nindent 4 }}
spec:
  type: {{ .Values.controlPlane.service.type }}
  ports:
    - name: http
      port: {{ .Values.controlPlane.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "crucible.selectorLabels" (dict "root" . "component" "control-plane") | nindent 4 }}
