{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crucible.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
  {{- $irsaArn := include "crucible.irsaRoleArn" . }}
  {{- if $irsaArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $irsaArn | quote }}
  {{- else }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
